### ISSUE TITLE
Cut new release v1.9.0 or v2.0.0

### ISSUE THREAD

**Issue by patcon** [sous-chefs/confluence#53]
It's been ages since we tagged a release. Happy to do it myself if #35 means people are comfortable giving me push access.

Also, on a related note, it would be really awesome if we started to keep the CHANGELOG up-to-date with changes :)

**Comment by thoutenbos** [comment]
+1

Would like an updated supermarkt release with a new (major) version

**Comment by patcon** [comment]
Ah, I see the conversation ended up moving here: https://github.com/parallels-cookbooks/confluence/pull/35#issuecomment-148985688

But I think this is the right place. Any reason we can't just cut a major release, then do those other important things after? We don't need to make a big event out of a major bump imho -- it's been almost 2 years, so let's just get this out and keep improving it after :)

**Comment by patcon** [comment]
From the issue linked above:
- [x] Fix unit-test failures
- [ ] Fix #63 - add asserts for attribute `node['mysql']['server_root_password']`
- [x] Port this change set from jira cookbook: #29
- [x] Port this change set from jira cookbook: #30

**Comment by legal90** [comment]
- [x] Update CHANGELOG.md for all changes made since the previous version.
- [ ] README.md: Describe database configuration according to the Atlassian's resrictions of Postgresql to {9.2, 9.3} and MySQL to {5.5, 5.6}. There should be some advices about default attribute values (refer to recipes in the fixture cookbook)

**Comment by legal90** [comment]
Finally, we did it: https://supermarket.chef.io/cookbooks/confluence/versions/2.0.0

**Comment by patcon** [comment]
:fireworks: :zap:

**Comment by thoutenbos** [comment]
Nice!

**Comment by gsreynolds** [comment]
:+1:
